### ISSUE TITLE
venv is missing inside the Docker image

### ISSUE THREAD

**Issue by seb2020** [nexsol-technologies/pgassistant#1]
Hi,

If you pull "nexsoltech/pgassistant:1.3" and do an inspection of the layer, it seems that all commands related to the venv are not present (https://github.com/nexsol-technologies/pgassistant/blob/main/Dockerfile#L21)

As a result, the image doesn't work on OpenShift, as not all libraries are available. 

If I rebuild the image from your image with this inside my Dockerfile, it's working fine

```
RUN python -m venv /home/pgassistant/venv
ENV PATH="/home/pgassistant/venv/bin:$PATH"

RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r /home/pgassistant/requirements.txt

RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r /home/pgassistant/requirements.txt
```

Can you check what's happening with the image build ?

**Comment by beh74** [comment]
Could you please pull again the 1.3 image. I have optimized the docker layers. Hope it will help !

**Comment by seb2020** [comment]
The new 1.3 is working fine, I will close this issue. Thanks
